    slip = [
        ["ID KARYAWAN", id_pilih, ""],
        ["NAMA", kar['NAMA KARYAWAN'], ""],
        ["PERIODE", f"{bulan}/{tahun}", f"{hari_kerja} hari"],
        ["", "", ""],
        ["=== PENDAPATAN ===", "", ""],
        ["GAJI POKOK", int(gaji_pokok), ""],
        ["PREMI HADIR", int(premi), ""],
        ["LOYALITAS", int(loyal), "Flat per bulan"],
        ["TOTAL MAKAN", int(total_makan), f"{hari_kerja} x {int(u_makan)}"],
        ["TOTAL SHIFT", int(total_shift), f"{hari_shift} x 2187.5"],
        ["JKK (0.24%)", int(jkk), "Perusahaan"],
        ["JKM (0.30%)", int(jkm), "Perusahaan"],
        ["JHT Perusahaan (3.7%)", int(jht_prsh), "Perusahaan"],
        ["JP Perusahaan (2%)", int(jp_prsh), "Perusahaan"],
        ["BPJS Kes Perusahaan (4%)", int(bpjs_kes_prsh), "Perusahaan"],
        ["", "", ""],
        ["TOTAL PENDAPATAN", int(total_pendapatan), "Gaji + Tunjangan + BPJS Prsh"],
        ["", "", ""],
        ["=== POTONGAN (LENGKAP) ===", "", ""],
        ["JKK (0.24%)", int(jkk), "Masuk potongan total"],
        ["JKM (0.30%)", int(jkm), "Masuk potongan total"],
        ["JHT Perusahaan (3.7%)", int(jht_prsh), "Masuk potongan total"],
        ["JP Perusahaan (2%)", int(jp_prsh), "Masuk potongan total"],
        ["BPJS Kes Perusahaan (4%)", int(bpjs_kes_prsh), "Masuk potongan total"],
        ["JHT TK (2%)", int(jht_tk), "Karyawan - MERAH"],
        ["JP TK (1%)", int(jp_tk), "Karyawan - MERAH"],
        ["BPJS Kes Karyawan (1%)", int(bpjs_kes_kar), "Karyawan - MERAH"],
        ["", "", ""],
        ["TOTAL POTONGAN", int(total_potongan), "748,011 = Jumlah semua 8 BPJS"],
        ["Rincian: BPJS Prsh", int(total_bpjs_perusahaan), "537,898"],
        ["Rincian: BPJS Karyawan", int(total_bpjs_karyawan), "210,116"],
        ["", "", ""],
        ["GAJI BERSIH / THP", int(gaji_bersih), "TOTAL PENDAPATAN - BPJS Karyawan"],
]
